services:
  web:
    build: .
    command: bash -c "/wait-for-it.sh db:5432 -- python app.py"
    volumes:
      - .:/app
      - transaction_files:/app/static/transaction_files
      - database_backups:/app/database_backups
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/office_services
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: office_services
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  transaction_files:
  database_backups: