services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins-net
    command: >-
      bash -c "
      apt-get update &&
      apt-get install -y curl &&
      curl -fsSL https://get.docker.com | sh &&
      curl -L \"https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose &&
      chmod +x /usr/local/bin/docker-compose &&
      /usr/local/bin/jenkins.sh
      "