version: '3.8'

services:
  web:
    build: .
    command: bash -c "sleep 10 && python app.py"
    tty: true 
    volumes:
      - .:/app
      - transaction_files:/app/static/transaction_files
      - database_backups:/app/database_backups
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/office_services
      SECRET_KEY: your_secret_key_here
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: office_services
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins:/var/jenkins_config
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: admin123
    command: >
      bash -c "
        cp /var/jenkins_config/*.groovy /usr/share/jenkins/ref/init.groovy.d/ &&
        /usr/local/bin/jenkins.sh
      "

volumes:
  postgres_data:
  transaction_files:
  database_backups:
  jenkins_data: